name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        run: |
          npm install
          npm run-script build
        env:
          ApiAirtable: ${{ variables.ApiAirtable }}
          AirtableBase: ${{ variables.AirtableBase }}
          SERVERLESS: ${{ variables.SERVERLESS }}

      - name: Deploy
        uses: wrongholt/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
